### ISSUE TITLE
Arduino Library Manager does not have the safety timer functions

### ISSUE THREAD

**Issue by cooper-david-a** [arduino-libraries/Arduino_BQ24195#50]
It seems the version of the library installed by the Arduino Library Manager is not the latest.
The version number is correct but the safety timer stuff is missing.

**Comment by per1234** [comment]
Hi @cooper-david-a.

> the safety timer stuff is missing

I'll assume you are referring to this:

https://github.com/arduino-libraries/Arduino_BQ24195/pull/22

It is expected this change is not present in the version installed by Library Manager. The reason is that the pull request has not been merged. It will only be distributed via the Library Manager after the following two events have happened:

1. The pull request is merged.
2. A new version of the library is released.
